docs: fix typos and add links (Ansible-Connection)
dhis2/dhis2-server-tools pull request #24
Opened 2023-10-23 12:53 UTC by iambaboucarr

Fixes typos and add link to ansible lxd plugin docs

2023-10-24 09:10 UTC, tkipkurgat requested changes
Thanks for your contribution, @babouceesay 
I've done a quick review, and there is one suggested change on community.general.lxd connection link.

2023-10-24 09:10 UTC, tkipkurgat commented on docs/Ansible-Connection.md
> +there is already a connection plugin available. It's the [lxd plugin](https://docs.ansible.com/ansible/latest/collections/community/general/lxd_container_module.html).
I think you meant this link. https://docs.ansible.com/ansible/latest/collections/community/general/lxd_connection.html,

2023-10-27 13:29 UTC, babouceesay commented
Thanks Tito for flagging that. I have applied the changes.

2023-11-06 15:43 UTC, tkipkurgat commented
I can confirm that the requested changes have been made,

2023-11-06 15:44 UTC, merged